eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/ # 注册中心地址
server:
  port: 9402
spring:
  application:
    name: component-comsumer
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: localhost
    virtual-host: my_vhost
feign:
  hystrix:
    enabled: true
