server:
  port: 9401
spring:
  application:
    name: component-provider
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    host: localhost
    virtual-host: my_vhost