server:
  port: 9300

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pgm-sup/configs
          search-paths: ./
          skip-ssl-validation: true
      label: master